"""add image field

Revision ID: 6507960102e1
Revises: 2ee19f332a20
Create Date: 2018-02-15 22:38:37.927575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6507960102e1'
down_revision = '2ee19f332a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('imgpath', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'imgpath')
    # ### end Alembic commands ###
